// <auto-generated />
using System;
using DSVHVN.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSVHVN.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928164123_KhoiTaoCsdl")]
    partial class KhoiTaoCsdl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Vietnamese_CI_AI")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DSVHVN.Domain.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("actor_role");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("target_type");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_audit_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_audit_logs_created_at");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Billing.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("due_at");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime?>("IssuedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("issued_at");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<long>("SubscriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("PK_invoices");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_invoices_invoice_number");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_invoices_status", "[status] IN ('UNPAID', 'PAID', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Billing.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("paid_at");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("provider_transaction_id");

                    b.Property<string>("RawResponse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_response");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK_payments");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProviderId", "ProviderTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_payments_provider_txn")
                        .HasFilter("[provider_transaction_id] IS NOT NULL");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_payments_status", "[status] IN ('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED')");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Billing.PaymentProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_payment_providers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_payment_providers_code");

                    b.ToTable("payment_providers", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Billing.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int")
                        .HasColumnName("duration_days");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("MaxAiRequests")
                        .HasColumnType("int")
                        .HasColumnName("max_ai_requests");

                    b.Property<int?>("MaxTeachers")
                        .HasColumnType("int")
                        .HasColumnName("max_teachers");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("PK_plans");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Billing.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK_subscriptions");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PlanId");

                    b.ToTable("subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_subscriptions_status", "[status] IN ('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Classes.SchoolClass", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("deleted_at");

                    b.Property<byte>("Grade")
                        .HasColumnType("tinyint")
                        .HasColumnName("grade");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<string>("SchoolYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("school_year");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_classes");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TeacherId");

                    b.ToTable("classes", null, t =>
                        {
                            t.HasCheckConstraint("CK_classes_grade", "[grade] BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Classes.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("1");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("student_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_students");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentCode")
                        .IsUnique()
                        .HasDatabaseName("UX_students_student_code");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_students_user_id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.Heritage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("HeritageType")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("heritage_type");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("place_id");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<string>("RecognitionLevel")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("recognition_level");

                    b.Property<int?>("RecognizedYear")
                        .HasColumnType("int")
                        .HasColumnName("recognized_year");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("short_description");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_heritages");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_heritages_slug");

                    b.ToTable("heritages", null, t =>
                        {
                            t.HasCheckConstraint("CK_heritages_heritage_type", "[heritage_type] IN ('TANGIBLE', 'INTANGIBLE', 'NATURAL', 'MIXED', 'DOCUMENTARY')");

                            t.HasCheckConstraint("CK_heritages_recognition_level", "[recognition_level] IN ('UNESCO', 'NATIONAL_SPECIAL', 'NATIONAL', 'PROVINCIAL', 'NONE')");

                            t.HasCheckConstraint("CK_heritages_status", "[status] IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.HeritageReference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("HeritageId")
                        .HasColumnType("bigint")
                        .HasColumnName("heritage_id");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("PK_heritage_references");

                    b.HasIndex("HeritageId");

                    b.ToTable("heritage_references", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.Media", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("caption");

                    b.Property<string>("Credit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("credit");

                    b.Property<long?>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<long?>("HeritageId")
                        .HasColumnType("bigint")
                        .HasColumnName("heritage_id");

                    b.Property<string>("MediaType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("media_type");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("PK_media");

                    b.HasIndex("EventId");

                    b.HasIndex("HeritageId");

                    b.ToTable("media", null, t =>
                        {
                            t.HasCheckConstraint("CK_media_owner", "(heritage_id IS NOT NULL AND event_id IS NULL) OR (heritage_id IS NULL AND event_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("region");

                    b.HasKey("Id")
                        .HasName("PK_provinces");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_provinces_code");

                    b.ToTable("provinces", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.Timeline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int")
                        .HasColumnName("end_year");

                    b.Property<long>("HeritageId")
                        .HasColumnType("bigint")
                        .HasColumnName("heritage_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int")
                        .HasColumnName("start_year");

                    b.HasKey("Id")
                        .HasName("PK_timelines");

                    b.HasIndex("HeritageId");

                    b.ToTable("timelines", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.TimelineEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<short?>("EndDay")
                        .HasColumnType("smallint")
                        .HasColumnName("end_day");

                    b.Property<short?>("EndMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("end_month");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int")
                        .HasColumnName("end_year");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<short?>("StartDay")
                        .HasColumnType("smallint")
                        .HasColumnName("start_day");

                    b.Property<short?>("StartMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("start_month");

                    b.Property<int>("StartYear")
                        .HasColumnType("int")
                        .HasColumnName("start_year");

                    b.Property<long>("TimelineId")
                        .HasColumnType("bigint")
                        .HasColumnName("timeline_id");

                    b.HasKey("Id")
                        .HasName("PK_events");

                    b.HasIndex("TimelineId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("used_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_password_reset_tokens_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_roles_code");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN",
                            Name = "Quản trị hệ thống"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ORG_ADMIN",
                            Name = "Quản trị trường"
                        },
                        new
                        {
                            Id = 3,
                            Code = "TEACHER",
                            Name = "Giáo viên"
                        },
                        new
                        {
                            Id = 4,
                            Code = "STUDENT",
                            Name = "Học sinh"
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Identity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit")
                        .HasColumnName("must_change_password")
                        .HasDefaultValueSql("0");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_users_email")
                        .HasFilter("[email] IS NOT NULL AND [deleted_at] IS NULL");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UX_users_username")
                        .HasFilter("[deleted_at] IS NULL");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_status", "[status] IN ('ACTIVE', 'LOCKED', 'INACTIVE')");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Lessons.AiGeneration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("InputSnapshot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("input_snapshot");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("Params")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("params");

                    b.Property<string>("RawOutput")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_output");

                    b.Property<long>("RequestedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TaskType")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("task_type");

                    b.HasKey("Id")
                        .HasName("PK_ai_generations");

                    b.HasIndex("LessonId");

                    b.HasIndex("RequestedBy");

                    b.ToTable("ai_generations", null, t =>
                        {
                            t.HasCheckConstraint("CK_ai_generations_status", "[status] IN ('PROCESSING', 'SUCCEEDED', 'FAILED')");

                            t.HasCheckConstraint("CK_ai_generations_task_type", "[task_type] IN ('LESSON_SUMMARY', 'QUIZ_GENERATION')");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Lessons.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("access_code");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("KeyPoints")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("key_points");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_lessons");

                    b.HasIndex("AccessCode")
                        .IsUnique()
                        .HasDatabaseName("UX_lessons_access_code")
                        .HasFilter("[access_code] IS NOT NULL");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("lessons", null, t =>
                        {
                            t.HasCheckConstraint("CK_lessons_status", "[status] IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Lessons.LessonHeritage", b =>
                {
                    b.Property<long>("LessonId")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<long>("HeritageId")
                        .HasColumnType("bigint")
                        .HasColumnName("heritage_id");

                    b.HasKey("LessonId", "HeritageId")
                        .HasName("PK_lesson_heritages");

                    b.HasIndex("HeritageId");

                    b.ToTable("lesson_heritages", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Organizations.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Questions.Answer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct")
                        .HasDefaultValueSql("0");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("PK_answers");

                    b.HasIndex("QuestionId");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Questions.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AiGenerationId")
                        .HasColumnType("bigint")
                        .HasColumnName("ai_generation_id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("explanation");

                    b.Property<long>("HeritageId")
                        .HasColumnType("bigint")
                        .HasColumnName("heritage_id");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("question_type");

                    b.Property<string>("ReviewStatus")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("review_status");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("reviewed_at");

                    b.Property<long?>("ReviewedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Source")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("source");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_questions");

                    b.HasIndex("AiGenerationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("HeritageId");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("questions", null, t =>
                        {
                            t.HasCheckConstraint("CK_questions_difficulty_level", "[difficulty_level] IN ('EASY', 'MEDIUM', 'HARD')");

                            t.HasCheckConstraint("CK_questions_question_type", "[question_type] IN ('SINGLE_CHOICE', 'TRUE_FALSE')");

                            t.HasCheckConstraint("CK_questions_review_status", "[review_status] IN ('PENDING', 'APPROVED', 'REJECTED')");

                            t.HasCheckConstraint("CK_questions_source", "[source] IN ('MANUAL', 'AI')");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Quizzes.Attempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CorrectCount")
                        .HasColumnType("int")
                        .HasColumnName("correct_count");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<long>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quiz_id");

                    b.Property<decimal?>("Score")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("score");

                    b.Property<DateTime?>("StartedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("submitted_at");

                    b.Property<decimal?>("TotalPoint")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("total_point");

                    b.Property<int?>("TotalQuestions")
                        .HasColumnType("int")
                        .HasColumnName("total_questions");

                    b.HasKey("Id")
                        .HasName("PK_attempts");

                    b.HasIndex("StudentId");

                    b.HasIndex("QuizId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_attempts_quiz_student");

                    b.ToTable("attempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_attempts_status", "[status] IN ('IN_PROGRESS', 'SUBMITTED', 'EXPIRED')");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Quizzes.AttemptAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AnswerId")
                        .HasColumnType("bigint")
                        .HasColumnName("answer_id");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("answered_at");

                    b.Property<long>("AttemptId")
                        .HasColumnType("bigint")
                        .HasColumnName("attempt_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("PointEarned")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("point_earned");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("PK_attempt_answers");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("UX_attempt_answers_attempt_question");

                    b.ToTable("attempt_answers", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Quizzes.Quiz", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CloseAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("close_at");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("difficulty_level");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("OpenAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("open_at");

                    b.Property<DateTime?>("PublishedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("published_at");

                    b.Property<bool>("ShowAnswersAfterSubmit")
                        .HasColumnType("bit")
                        .HasColumnName("show_answers_after_submit")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("bit")
                        .HasColumnName("shuffle_questions")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("int")
                        .HasColumnName("time_limit_minutes");

                    b.Property<decimal?>("TotalPoint")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("total_point");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_quizzes");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LessonId");

                    b.ToTable("quizzes", null, t =>
                        {
                            t.HasCheckConstraint("CK_quizzes_difficulty_level", "[difficulty_level] IN ('EASY', 'MEDIUM', 'HARD')");

                            t.HasCheckConstraint("CK_quizzes_status", "[status] IN ('DRAFT', 'PUBLISHED', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("DSVHVN.Domain.Quizzes.QuizQuestion", b =>
                {
                    b.Property<long>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quiz_id");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<decimal?>("Point")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("point");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("QuizId", "QuestionId")
                        .HasName("PK_quiz_questions");

                    b.HasIndex("QuestionId");

                    b.ToTable("quiz_questions", (string)null);
                });

            modelBuilder.Entity("DSVHVN.Domain.Audit.AuditLog", b =>
                {
                    b.HasOne("DSVHVN.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_user_id");
                });

            modelBuilder.Entity("DSVHVN.Domain.Billing.Invoice", b =>
                {
                    b.HasOne("DSVHVN.Domain.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_organization_id");

                    b.HasOne("DSVHVN.Domain.Billing.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_subscription_id");

                    b.Navigation("Organization");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("DSVHVN.Domain.Billing.Payment", b =>
                {
                    b.HasOne("DSVHVN.Domain.Billing.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_invoice_id");

                    b.HasOne("DSVHVN.Domain.Billing.PaymentProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_provider_id");

                    b.Navigation("Invoice");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("DSVHVN.Domain.Billing.Subscription", b =>
                {
                    b.HasOne("DSVHVN.Domain.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_organization_id");

                    b.HasOne("DSVHVN.Domain.Billing.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_plan_id");

                    b.Navigation("Organization");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("DSVHVN.Domain.Classes.SchoolClass", b =>
                {
                    b.HasOne("DSVHVN.Domain.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_organization_id");

                    b.HasOne("DSVHVN.Domain.Identity.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_teacher_id");

                    b.Navigation("Organization");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DSVHVN.Domain.Classes.Student", b =>
                {
                    b.HasOne("DSVHVN.Domain.Classes.SchoolClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_students_class_id");

                    b.HasOne("DSVHVN.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_students_user_id");

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.Heritage", b =>
                {
                    b.HasOne("DSVHVN.Domain.Heritages.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_heritages_province_id");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.HeritageReference", b =>
                {
                    b.HasOne("DSVHVN.Domain.Heritages.Heritage", "Heritage")
                        .WithMany("References")
                        .HasForeignKey("HeritageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_heritage_references_heritage_id");

                    b.Navigation("Heritage");
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.Media", b =>
                {
                    b.HasOne("DSVHVN.Domain.Heritages.TimelineEvent", "Event")
                        .WithMany("Media")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_media_event_id");

                    b.HasOne("DSVHVN.Domain.Heritages.Heritage", "Heritage")
                        .WithMany("Media")
                        .HasForeignKey("HeritageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_media_heritage_id");

                    b.Navigation("Event");

                    b.Navigation("Heritage");
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.Timeline", b =>
                {
                    b.HasOne("DSVHVN.Domain.Heritages.Heritage", "Heritage")
                        .WithMany("Timelines")
                        .HasForeignKey("HeritageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_timelines_heritage_id");

                    b.Navigation("Heritage");
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.TimelineEvent", b =>
                {
                    b.HasOne("DSVHVN.Domain.Heritages.Timeline", "Timeline")
                        .WithMany("Events")
                        .HasForeignKey("TimelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_timeline_id");

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("DSVHVN.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("DSVHVN.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DSVHVN.Domain.Identity.User", b =>
                {
                    b.HasOne("DSVHVN.Domain.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_organization_id");

                    b.HasOne("DSVHVN.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_role_id");

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DSVHVN.Domain.Lessons.AiGeneration", b =>
                {
                    b.HasOne("DSVHVN.Domain.Lessons.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ai_generations_lesson_id");

                    b.HasOne("DSVHVN.Domain.Identity.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ai_generations_requested_by");

                    b.Navigation("Lesson");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("DSVHVN.Domain.Lessons.Lesson", b =>
                {
                    b.HasOne("DSVHVN.Domain.Classes.SchoolClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_class_id");

                    b.HasOne("DSVHVN.Domain.Identity.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_teacher_id");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DSVHVN.Domain.Lessons.LessonHeritage", b =>
                {
                    b.HasOne("DSVHVN.Domain.Heritages.Heritage", "Heritage")
                        .WithMany()
                        .HasForeignKey("HeritageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_heritages_heritage_id");

                    b.HasOne("DSVHVN.Domain.Lessons.Lesson", "Lesson")
                        .WithMany("Heritages")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_heritages_lesson_id");

                    b.Navigation("Heritage");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DSVHVN.Domain.Questions.Answer", b =>
                {
                    b.HasOne("DSVHVN.Domain.Questions.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_answers_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DSVHVN.Domain.Questions.Question", b =>
                {
                    b.HasOne("DSVHVN.Domain.Lessons.AiGeneration", "AiGeneration")
                        .WithMany()
                        .HasForeignKey("AiGenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_questions_ai_generation_id");

                    b.HasOne("DSVHVN.Domain.Identity.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_created_by");

                    b.HasOne("DSVHVN.Domain.Heritages.Heritage", "Heritage")
                        .WithMany()
                        .HasForeignKey("HeritageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_heritage_id");

                    b.HasOne("DSVHVN.Domain.Identity.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_questions_reviewed_by");

                    b.Navigation("AiGeneration");

                    b.Navigation("Creator");

                    b.Navigation("Heritage");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("DSVHVN.Domain.Quizzes.Attempt", b =>
                {
                    b.HasOne("DSVHVN.Domain.Quizzes.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempts_quiz_id");

                    b.HasOne("DSVHVN.Domain.Classes.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempts_student_id");

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DSVHVN.Domain.Quizzes.AttemptAnswer", b =>
                {
                    b.HasOne("DSVHVN.Domain.Questions.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attempt_answers_answer_id");

                    b.HasOne("DSVHVN.Domain.Quizzes.Attempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_answers_attempt_id");

                    b.HasOne("DSVHVN.Domain.Questions.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_answers_question_id");

                    b.Navigation("Answer");

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DSVHVN.Domain.Quizzes.Quiz", b =>
                {
                    b.HasOne("DSVHVN.Domain.Identity.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quizzes_created_by");

                    b.HasOne("DSVHVN.Domain.Lessons.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quizzes_lesson_id");

                    b.Navigation("Creator");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DSVHVN.Domain.Quizzes.QuizQuestion", b =>
                {
                    b.HasOne("DSVHVN.Domain.Questions.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_questions_question_id");

                    b.HasOne("DSVHVN.Domain.Quizzes.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_questions_quiz_id");

                    b.Navigation("Question");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.Heritage", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("References");

                    b.Navigation("Timelines");
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.Timeline", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("DSVHVN.Domain.Heritages.TimelineEvent", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("DSVHVN.Domain.Lessons.Lesson", b =>
                {
                    b.Navigation("Heritages");
                });

            modelBuilder.Entity("DSVHVN.Domain.Questions.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("DSVHVN.Domain.Quizzes.Attempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("DSVHVN.Domain.Quizzes.Quiz", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
