<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DSVHVN.Api\DSVHVN.Api.csproj" />
    <ProjectReference Include="..\..\src\DSVHVN.Application\DSVHVN.Application.csproj" />
    <ProjectReference Include="..\..\src\DSVHVN.Domain\DSVHVN.Domain.csproj" />
    <ProjectReference Include="..\..\src\DSVHVN.Infrastructure\DSVHVN.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.20" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
